services:
  - type: web
    name: wdaweb-backend-redesign
    env: python
    rootDir: server
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
